import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: "../fonts/JetBrainsMono/JetBrainsMono-Medium.woff2",
  display: "swap",
  variable: "--font-jet-brains-mono",
});

export const metadata: Metadata = {
  title: "Hobby-Hub",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.variable}>
        <main className="p-6 w-screen text-base flex flex-col gap-2 h-screen font-mono">
          {children}
        </main>
      </body>
    </html>
  );
}
