import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import NavMenu from "./components/NavMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hobby-Hub",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <SessionProvider session={session}> */}
        <main className="p-6 w-screen text-base flex flex-col gap-2 h-screen font-mono">
          <NavMenu />
          {children}
        </main>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
